# Generated by Django 3.1.2 on 2020-10-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
