# Generated by Django 3.1.2 on 2020-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20201021_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN'),
        ),
    ]
