# Generated by Django 3.1.2 on 2020-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20201021_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ilość stron'),
        ),
    ]
