# Generated by Django 3.1.2 on 2020-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20201022_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Autor'),
        ),
    ]
